Vladimir Litvyakov: Homework 4 completed
eugene-okulik/Flapsya pull request #3
Opened 2024-05-10 13:29 UTC by VladimirLitvyakov-qa

2024-05-11 10:28 UTC, eugene-okulik approved these changes
Всё хорошо, но одну проверочку на внимательность не прошел.

2024-05-11 10:28 UTC, eugene-okulik commented on homework/vladimir_litvyakov/homework_4/task.py
> +my_dict['dict']['i am a tuple'] = 'test'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-05-11 10:28 UTC, eugene-okulik requested changes
Случайно нажал Approve

2024-05-12 05:45 UTC, VladimirLitvyakov-qa commented
Исправил строку на кортеж, при этом указал кортеж как string. Без указания питон ругается "Expected type 'str | int' (matched generic type '_KT'), got 'tuple[str, int]' instead" - как я понял, ключ в списке это неизменяемое значение => нужно указывать str или int)

2024-05-12 05:46 UTC, VladimirLitvyakov-qa commented
Исправил строку на кортеж, при этом указал кортеж как string. Без указания питон ругается "Expected type 'str | int' (matched generic type '_KT'), got 'tuple[str, int]' instead" - как я понял, ключ в списке это неизменяемое значение => нужно указывать str или int)

2024-05-15 09:03 UTC, eugene-okulik approved these changes

2024-05-15 09:03 UTC, merged