Vladimir Litvyakov: homework 5 completed
eugene-okulik/Flapsya pull request #4
Opened 2024-05-16 05:52 UTC by VladimirLitvyakov-qa

2024-05-16 10:34 UTC, eugene-okulik requested changes

2024-05-16 10:34 UTC, eugene-okulik commented on homework/vladimir_litvyakov/homework_5/task_1.py
> +country = person[4]
В питоне считается, что нужно всяческими способами избегать обращения к элементам списка по индексу. И здесь бы таким способом была бы распаковка. В видео я рассказывал о ней.

2024-05-16 10:34 UTC, eugene-okulik commented on homework/vladimir_litvyakov/homework_5/task_2.py
Ты, судя по всему, не понял задание.  
Вот есть какая-то программа. И мы получаем от нее результат ее работы. Мы к ней обратились 3 раза и сохранили то, что она ответила в 3 разные переменные. И вот нам нужно написать код, который найдет в ответе программы число и сделает с ним то, что написано в задании.  
Нам нужно сделать один код, который сможет работать с любым из вариантов ответа. То есть обработать каждую переменную абсолютно одинаковым кодом. Пока что делаем это копируя код, потом будем учиться как избежать здесь этого копирования.  
Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.

2024-05-17 04:31 UTC, VladimirLitvyakov-qa commented on homework/vladimir_litvyakov/homework_5/task_2.py
Привет, помимо кода который закоммитил так же думал сделать так:

2024-05-17 09:20 UTC, eugene-okulik commented on homework/vladimir_litvyakov/homework_5/task_2.py
Второй вариант более оптимальный. Если бы в задании не было требования все сделать с помощью индекса и срезов, то он был бы более подходящим. Только я бы брал на всякие случай не второй элемент, а последний `[-1]`  
Здесь у нас выбор из двух костыльных решений. Просто второе чуть менее костыльное, поэтому, оно более оптимальное.

2024-05-17 09:21 UTC, eugene-okulik approved these changes

2024-05-17 09:22 UTC, merged